Repository matcornic/hugo-theme-learn, pull requests merged in 2019-03, with the labels that each got.

#250 Use style instead of width and height in logo
  layouts/partials/logo.html
Labels: enhancement

#224 Add .editorconfig
  .editorconfig
Labels: meta

#234 Fix translation when using a custom baseURL
  layouts/partials/menu.html
Labels: bug
