Repository matcornic/hugo-theme-learn, pull requests merged in 2019-02, with the labels that each got.

#229 Update menu.html to include the check icon
  layouts/partials/menu.html
Labels: bug

#241 Preventing left/right arrow key navigation in textareas
  static/js/learn.js
Labels: bug

#223 HTTPS links in exampleSite menu-footer
  exampleSite/layouts/partials/menu-footer.html
Labels: enhancement

#239 Dutch i18n
  i18n/nl.toml
Labels: i18n

#227 remove duplicate icon and fix incorrect favicon type
  layouts/partials/favicon.html
Labels: enhancement
