Repository matcornic/hugo-theme-learn, pull requests merged in 2020-02, with the labels that each got.

#345 fix select option color in Chrome
  static/css/theme.css
Labels: bug

#320 remove unneeded spaces from HTML
  layouts/_default/single.html
Labels: bug

#331 add inteliver documentation showcase
  exampleSite/content/showcase.en.md
  exampleSite/content/showcase.fr.md
  exampleSite/static/images/showcase/inteliver_docs.png
Labels: meta

#333 Added flag to turn off image featherlight
  exampleSite/content/cont/markdown.en.md
  static/js/hugo-learn.js
Labels: feature

#354 Avoid displaying hidden sections in menu
  layouts/partials/menu.html
Labels: bug
