Repository matcornic/hugo-theme-learn, pull requests merged in 2020-09, with the labels that each got.

#424 Remove extra space
  exampleSite/content/shortcodes/attachments.en.md
Labels: bug

#422 Remove extra space
  exampleSite/content/cont/archetypes.en.md
Labels: bug

#425 Fix children shortcode table
  exampleSite/content/shortcodes/children/_index.en.md
Labels: bug

#427 Make copy to clipboard button more obvious, make hover match link color
  static/css/theme.css
Labels: enhancement

#423 Fix typo
  exampleSite/content/shortcodes/attachments.en.md
Labels: enhancement

#446 Update netlify baseurl fixes #438
  netlify.toml
Labels: bug

#443 Upgrade mermaid-js/mermaid @ 0918b97 (v8.8.0)
  exampleSite/content/shortcodes/mermaid.en.md
  exampleSite/content/shortcodes/mermaid.fr.md
  static/mermaid/mermaid.js
Labels: enhancement

#419 Remove code that adjusts navigation margin
  static/js/learn.js
Labels: enhancement

#416 fix: closing div tag
  layouts/shortcodes/attachments.html
Labels: bug

#444 fix: change taxonomy term and use taxonomy name
  layouts/_default/list.html
  layouts/partials/header.html
Labels: bug

#448 Add the titleSeparator parameter.
  exampleSite/config.toml
  exampleSite/content/basics/configuration/_index.en.md
  layouts/partials/header.html
Labels: feature

#362 Customize mermaid module
  exampleSite/config.toml
  exampleSite/content/basics/configuration/_index.en.md
  exampleSite/content/basics/configuration/_index.fr.md
  exampleSite/content/shortcodes/mermaid.en.md
  exampleSite/content/shortcodes/mermaid.fr.md
  layouts/partials/footer.html
  static/mermaid/mermaid.css
  static/mermaid/mermaid.dark.css
  static/mermaid/mermaid.forest.css
Labels: feature
