Repository matcornic/hugo-theme-learn, pull requests merged in 2021-03, with the labels that each got.

#386 Implement tab views
  exampleSite/content/shortcodes/tabs.en.md
  layouts/partials/header.html
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
  static/css/tabs.css
  static/js/learn.js
Labels: feature

#479 Fix TOC indentation
  static/css/hugo-theme.css
Labels: enhancement

#470 Don't count hidden pages for the sub-menus
  layouts/partials/menu.html
Labels: bug

#492 fix potential XSS in search
  static/js/search.js
Labels: bug
